<a href="https://colab.research.google.com/github/LucasDatilioCarderelli/-QuarentenaDados/blob/master/Resultado_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

In [0]:
dados_previsao = pd.read_csv("https://raw.githubusercontent.com/LucasDatilioCarderelli/-QuarentenaDados/master/PREDICAO_DESAFIOQT.csv")
dados_validacao = pd.read_csv("https://raw.githubusercontent.com/LucasDatilioCarderelli/-QuarentenaDados/master/DADOS_VALIDACAO_SEED_845309_LC.csv", sep=',')

In [3]:
dados_previsao = dados_previsao.drop("ID", axis=1)
dados_previsao = dados_previsao.to_numpy().reshape(-1,1)
dados_previsao

array([[501.94877182],
       [584.15002273],
       [519.20458881],
       ...,
       [530.76498573],
       [576.65384219],
       [502.3147838 ]])

In [4]:
dados_validacao = dados_validacao.drop("ID", axis=1)
dados_validacao = dados_validacao.to_numpy().reshape(-1,1)
dados_validacao

array([[503. ],
       [625.1],
       [534.7],
       ...,
       [584.5],
       [554.9],
       [482.7]])

In [5]:
avaliação = mean_squared_error(dados_previsao, dados_validacao)
avaliação

2037.5712039860994

- Humberto Pereira, atingiu um MSE de 2008.958117
- 10º atingiu um MSE de 2029.730915169531

In [6]:
dados_valid = pd.read_csv("/content/DADOS_VALIDACAO_SEED_845309.csv")
dados_valid = dados_valid["NU_NOTA_LC"].to_numpy().reshape(-1,1)
dados_valid

array([[503. ],
       [625.1],
       [534.7],
       ...,
       [584.5],
       [554.9],
       [482.7]])

In [8]:
avaliação_prova = mean_squared_error(dados_valid, dados_validacao)
avaliação_prova

0.0